### ISSUE TITLE
Wiki is not up to date!

### ISSUE THREAD

**Issue by ghost** [epichickensoup/hello-world2#2]
The wiki seems to have left off a bad note, the owner of the repo did not state whether or whether not popgoesme700 can edit the wiki, while currently it states they he can not, the revision history seems to be lying, including the most recent on as of this issue post. Please fix, otherwise i may not have a clue on whether or whether not popgoesme700 can edit the wiki.

**Comment by epichickensoup** [comment]
popgoesme700 appears to be able to edit the wiki, so it has been updated as thus!

(this message was edited to inform you that I pressed the "Close with comment" button.)
